### ISSUE TITLE
Error: the queried row count exceeds the expected limit based on the pagination params

### ISSUE THREAD

**Issue by erakis** [brietsparks/knex-relay-cursor-pagination#5]
Hi,

I always get the following error: `the queried row count exceeds the expected limit based on the pagination params`

Am I doing something incorrect? I don't understand.

Database: `PostgreSQL 15`
Node: `18.14`
OS: Windows `10`
I'm not using `Typescript` but only `Javascript`

Here is what I'm doing

```js
  const pagination = createPagination({
    from: 'user',
    sortColumn: 'first_name',
    sortDirection: 'desc',
    cursorColumn: 'id',
    first: 10,
  });

  const rows = databaseConnection
    .select(
      'user.id',
      'user.email',
      'user.first_name',
      'user.last_name',
    )
    .from('user')
    .where(
      pagination.where.column,
      pagination.where.comparator,
      pagination.where.value,
    )
    .orderBy(pagination.orderBy.column, pagination.orderBy.direction)
    .limit(pagination.limit);

  return pagination.getPage(rows);
```

However, my query returns more than 300 users when I run `rows` directly.

```js
 databaseConnection
    .select(
      'user.id',
      'user.email',
      'user.first_name',
      'user.last_name',
    )
    .from('user')
```

**Comment by brietsparks** [comment]
Hi @erakis 

Sorry to hear you're running into this error. I tried to replicate your problem but got the paginated rows without error.  See [here](https://github.com/brietsparks/knex-relay-cursor-pagination/blob/issue-5-diagnose/test/example.test.js#L68) in branch `issue-5-diagnose` (note, I changed `user` table to `users`). You can run it by cloning the repo, checking out branch `issue-5-diagnose`, installing the node deps, and then running `yarn test test/example.test.ts`

**Comment by erakis** [comment]
> Hi @erakis
> 
> Sorry to hear you're running into this error. I tried to replicate your problem but got the paginated rows without error. See [here](https://github.com/brietsparks/knex-relay-cursor-pagination/blob/issue-5-diagnose/test/example.test.js#L68) in branch `issue-5-diagnose` (note, I changed `user` table to `users`). You can run it by cloning the repo, checking out branch `issue-5-diagnose`, installing the node deps, and then running `yarn test test/example.test.ts`

@brietsparks I will have to remove `createPgTestcontainer` from `example.test.ts` as last time I tried to run it, it failed with an error about UNIX pipe missing. I'm running Docker on Windows 10.

But now that I think about it, maybe I have an idea as to why it doesn't work!  Since I don't use the `await/async` mode, I would need a `.then` before calling the `getPage`?

**Comment by brietsparks** [comment]
> But now that I think about it, maybe I have an idea as to why it doesn't work! Since I don't use the await/async mode, I would need a .then before calling the getPage?

Ah, yep, that seems like that's the problem
